begin;

create or replace function public.hq_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.hq_worldcups (
  id bigint generated by default as identity primary key,
  legacy_cup_id text not null unique,
  title text not null,
  icon text not null default '🏆',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hq_worldcup_candidates (
  id bigint generated by default as identity primary key,
  worldcup_id bigint not null references public.hq_worldcups(id) on delete cascade,
  legacy_candidate_id text not null,
  name text not null,
  occurred_on date,
  source_url text,
  media_url text,
  media_type text not null default 'text' check (media_type in ('image', 'video', 'text')),
  width integer not null default 0 check (width >= 0),
  height integer not null default 0 check (height >= 0),
  poster_url text,
  win_count bigint not null default 0 check (win_count >= 0),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (worldcup_id, legacy_candidate_id)
);

drop trigger if exists hq_worldcups_updated_at on public.hq_worldcups;
create trigger hq_worldcups_updated_at before update on public.hq_worldcups
for each row execute function public.hq_set_updated_at();

drop trigger if exists hq_worldcup_candidates_updated_at on public.hq_worldcup_candidates;
create trigger hq_worldcup_candidates_updated_at before update on public.hq_worldcup_candidates
for each row execute function public.hq_set_updated_at();

create index if not exists hq_worldcups_sort_idx on public.hq_worldcups (is_active, sort_order, id);
create index if not exists hq_worldcup_candidates_cup_idx on public.hq_worldcup_candidates (worldcup_id, is_active, sort_order, id);
create index if not exists hq_worldcup_candidates_rank_idx on public.hq_worldcup_candidates (worldcup_id, win_count desc, id);

alter table public.hq_worldcups enable row level security;
alter table public.hq_worldcup_candidates enable row level security;

drop policy if exists hq_worldcups_public_read on public.hq_worldcups;
create policy hq_worldcups_public_read on public.hq_worldcups
for select to anon, authenticated using (is_active);

drop policy if exists hq_worldcup_candidates_public_read on public.hq_worldcup_candidates;
create policy hq_worldcup_candidates_public_read on public.hq_worldcup_candidates
for select to anon, authenticated using (is_active);

revoke insert, update, delete on public.hq_worldcups from anon, authenticated;
revoke insert, update, delete on public.hq_worldcup_candidates from anon, authenticated;
grant select on public.hq_worldcups, public.hq_worldcup_candidates to anon, authenticated;

create or replace view public.hq_worldcup_public
with (security_invoker = true)
as
select
  cup.id,
  cup.legacy_cup_id,
  cup.title,
  cup.icon,
  cup.sort_order,
  count(candidate.id)::bigint as candidate_count
from public.hq_worldcups cup
left join public.hq_worldcup_candidates candidate
  on candidate.worldcup_id = cup.id and candidate.is_active = true
where cup.is_active = true
group by cup.id, cup.legacy_cup_id, cup.title, cup.icon, cup.sort_order;

grant select on public.hq_worldcup_public to anon, authenticated;

create or replace function public.hq_record_worldcup_win(p_candidate_id bigint)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  next_count bigint;
begin
  update public.hq_worldcup_candidates
  set win_count = win_count + 1
  where id = p_candidate_id and is_active = true
  returning win_count into next_count;
  if next_count is null then raise exception 'Candidate not found'; end if;
  return next_count;
end;
$$;

revoke all on function public.hq_record_worldcup_win(bigint) from public;
grant execute on function public.hq_record_worldcup_win(bigint) to anon, authenticated;

commit;
