create table if not exists public.hq_view_events (
  id bigint generated by default as identity primary key,
  viewed_at timestamptz not null default now(),
  viewed_on date not null default ((now() at time zone 'Asia/Seoul')::date),
  event_type text not null check (event_type in ('tab', 'content')),
  tab_key text not null check (tab_key in ('home', 'calendar', 'recommended', 'postype')),
  content_type text check (content_type is null or content_type in ('hq_archive', 'recommended_video', 'postype')),
  content_id text,
  content_title text,
  content_url text,
  session_id text,
  path text,
  referrer text,
  user_agent text
);

alter table public.hq_view_events enable row level security;

create index if not exists hq_view_events_viewed_on_idx
on public.hq_view_events (viewed_on desc, viewed_at desc);

create index if not exists hq_view_events_tab_idx
on public.hq_view_events (tab_key, viewed_on desc);

create index if not exists hq_view_events_content_idx
on public.hq_view_events (content_type, content_id, viewed_on desc);

drop policy if exists hq_view_events_public_insert on public.hq_view_events;
create policy hq_view_events_public_insert
on public.hq_view_events
for insert
to anon, authenticated
with check (
  event_type in ('tab', 'content')
  and tab_key in ('home', 'calendar', 'recommended', 'postype')
  and (content_type is null or content_type in ('hq_archive', 'recommended_video', 'postype'))
  and char_length(coalesce(content_id, '')) <= 160
  and char_length(coalesce(content_title, '')) <= 500
  and char_length(coalesce(content_url, '')) <= 1000
  and char_length(coalesce(session_id, '')) <= 80
  and char_length(coalesce(path, '')) <= 500
  and char_length(coalesce(referrer, '')) <= 500
  and char_length(coalesce(user_agent, '')) <= 500
);

revoke all on public.hq_view_events from anon, authenticated;
grant insert on public.hq_view_events to anon, authenticated;
grant usage, select on sequence public.hq_view_events_id_seq to anon, authenticated;

create or replace function public.hq_admin_view_daily(
  p_from date,
  p_to date
)
returns table (
  viewed_on date,
  views bigint,
  tab_views bigint,
  content_views bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    event.viewed_on,
    count(*)::bigint as views,
    count(*) filter (where event.event_type = 'tab')::bigint as tab_views,
    count(*) filter (where event.event_type = 'content')::bigint as content_views
  from public.hq_view_events event
  where event.viewed_on between p_from and p_to
  group by event.viewed_on
  order by event.viewed_on desc;
$$;

create or replace function public.hq_admin_view_tabs(
  p_from date,
  p_to date
)
returns table (
  tab_key text,
  views bigint,
  content_views bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    event.tab_key,
    count(*)::bigint as views,
    count(*) filter (where event.event_type = 'content')::bigint as content_views
  from public.hq_view_events event
  where event.viewed_on between p_from and p_to
  group by event.tab_key
  order by views desc, tab_key asc;
$$;

create or replace function public.hq_admin_view_content(
  p_from date,
  p_to date,
  p_query text default '',
  p_offset integer default 0,
  p_limit integer default 30
)
returns table (
  content_type text,
  content_id text,
  content_title text,
  content_url text,
  tab_key text,
  views bigint,
  last_viewed_at timestamptz,
  total_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with filtered as (
    select *
    from public.hq_view_events event
    where event.event_type = 'content'
      and event.viewed_on between p_from and p_to
      and (
        coalesce(trim(p_query), '') = ''
        or event.content_title ilike '%' || trim(p_query) || '%'
        or event.content_url ilike '%' || trim(p_query) || '%'
        or event.content_id ilike '%' || trim(p_query) || '%'
        or event.tab_key ilike '%' || trim(p_query) || '%'
        or event.content_type ilike '%' || trim(p_query) || '%'
      )
  ),
  grouped as (
    select
      filtered.content_type,
      filtered.content_id,
      coalesce(max(nullif(filtered.content_title, '')), '(제목 없음)') as content_title,
      max(nullif(filtered.content_url, '')) as content_url,
      coalesce(max(nullif(filtered.tab_key, '')), 'home') as tab_key,
      count(*)::bigint as views,
      max(filtered.viewed_at) as last_viewed_at
    from filtered
    group by filtered.content_type, filtered.content_id
  )
  select
    grouped.content_type,
    grouped.content_id,
    grouped.content_title,
    grouped.content_url,
    grouped.tab_key,
    grouped.views,
    grouped.last_viewed_at,
    count(*) over()::bigint as total_count
  from grouped
  order by grouped.views desc, grouped.last_viewed_at desc
  offset greatest(p_offset, 0)
  limit least(greatest(p_limit, 1), 100);
$$;

revoke all on function public.hq_admin_view_daily(date, date) from public, anon, authenticated;
revoke all on function public.hq_admin_view_tabs(date, date) from public, anon, authenticated;
revoke all on function public.hq_admin_view_content(date, date, text, integer, integer) from public, anon, authenticated;
grant execute on function public.hq_admin_view_daily(date, date) to service_role;
grant execute on function public.hq_admin_view_tabs(date, date) to service_role;
grant execute on function public.hq_admin_view_content(date, date, text, integer, integer) to service_role;
