begin;

create table if not exists public.hq_search_events (
  id bigint generated by default as identity primary key,
  searched_at timestamptz not null default now(),
  searched_on date not null default ((now() at time zone 'Asia/Seoul')::date),
  query_text text not null,
  query_kind text not null check (query_kind in ('title', 'keyword', 'date')),
  result_count integer not null default 0 check (result_count >= 0),
  tab_key text not null default 'home' check (tab_key in ('home', 'calendar', 'recommended')),
  session_id text,
  path text
);

create index if not exists hq_search_events_date_idx on public.hq_search_events (searched_on desc, searched_at desc);
create index if not exists hq_search_events_query_idx on public.hq_search_events (query_kind, query_text, searched_on desc);
alter table public.hq_search_events enable row level security;

drop policy if exists hq_search_events_public_insert on public.hq_search_events;
create policy hq_search_events_public_insert on public.hq_search_events for insert to anon, authenticated
with check (
  char_length(query_text) between 1 and 300
  and query_kind in ('title', 'keyword', 'date')
  and result_count between 0 and 1000000
  and tab_key in ('home', 'calendar', 'recommended')
  and char_length(coalesce(session_id, '')) <= 80
  and char_length(coalesce(path, '')) <= 500
);

revoke all on public.hq_search_events from anon, authenticated;
grant insert on public.hq_search_events to anon, authenticated;
grant usage, select on sequence public.hq_search_events_id_seq to anon, authenticated;

create or replace function public.hq_admin_search_stats(p_from date, p_to date, p_limit integer default 20)
returns jsonb language sql stable security definer set search_path = public as $$
  with filtered as (
    select * from public.hq_search_events
    where searched_on between least(p_from, p_to) and greatest(p_from, p_to)
  ), top_queries as (
    select query_kind, query_text, count(*)::bigint searches,
      count(distinct session_id)::bigint visitors,
      count(*) filter (where result_count = 0)::bigint zero_results,
      max(searched_at) last_searched_at
    from filtered group by query_kind, query_text
    order by searches desc, last_searched_at desc
    limit least(greatest(p_limit, 1), 20)
  ), recent as (
    select searched_at, searched_on, query_kind, query_text, result_count, tab_key
    from filtered order by searched_at desc limit 100
  )
  select jsonb_build_object(
    'totals', jsonb_build_object(
      'searches', (select count(*) from filtered),
      'visitors', (select count(distinct session_id) from filtered),
      'zeroResults', (select count(*) from filtered where result_count = 0)
    ),
    'top', coalesce((select jsonb_agg(to_jsonb(top_queries) order by searches desc, last_searched_at desc) from top_queries), '[]'::jsonb),
    'recent', coalesce((select jsonb_agg(to_jsonb(recent) order by searched_at desc) from recent), '[]'::jsonb)
  );
$$;

revoke all on function public.hq_admin_search_stats(date, date, integer) from public, anon, authenticated;
grant execute on function public.hq_admin_search_stats(date, date, integer) to service_role;

create or replace function public.hq_admin_view_content(
  p_from date, p_to date, p_query text default '', p_offset integer default 0, p_limit integer default 30
)
returns table (
  content_type text, content_id text, content_title text, content_url text, tab_key text,
  views bigint, last_viewed_at timestamptz, total_count bigint
)
language sql stable security definer set search_path = public as $$
  with filtered as (
    select * from public.hq_view_events event
    where event.event_type = 'content'
      and event.content_type in ('hq_archive', 'recommended_video')
      and event.viewed_on between p_from and p_to
      and (coalesce(trim(p_query), '') = '' or event.content_title ilike '%' || trim(p_query) || '%'
        or event.content_url ilike '%' || trim(p_query) || '%' or event.content_id ilike '%' || trim(p_query) || '%'
        or event.tab_key ilike '%' || trim(p_query) || '%' or event.content_type ilike '%' || trim(p_query) || '%')
  ), grouped as (
    select filtered.content_type, filtered.content_id,
      coalesce(max(nullif(filtered.content_title, '')), '(제목 없음)') content_title,
      max(nullif(filtered.content_url, '')) content_url, filtered.tab_key,
      count(*)::bigint views, max(filtered.viewed_at) last_viewed_at
    from filtered group by filtered.content_type, filtered.content_id, filtered.tab_key
  )
  select grouped.*, count(*) over()::bigint total_count from grouped
  order by grouped.views desc, grouped.last_viewed_at desc
  offset greatest(p_offset, 0) limit least(greatest(p_limit, 1), 100);
$$;

revoke all on function public.hq_admin_view_content(date, date, text, integer, integer) from public, anon, authenticated;
grant execute on function public.hq_admin_view_content(date, date, text, integer, integer) to service_role;

commit;
