begin;

create table if not exists public.hq_worldcup_click_events (
  id bigint generated by default as identity primary key,
  clicked_at timestamptz not null default now(),
  clicked_on date not null default ((now() at time zone 'Asia/Seoul')::date),
  worldcup_key text not null,
  worldcup_title text not null,
  bracket_size integer not null default 0 check (bracket_size >= 0),
  session_id text,
  path text,
  referrer text
);

create index if not exists hq_worldcup_click_events_date_idx
on public.hq_worldcup_click_events (clicked_on desc, clicked_at desc);

create index if not exists hq_worldcup_click_events_cup_idx
on public.hq_worldcup_click_events (worldcup_key, clicked_on desc);

alter table public.hq_worldcup_click_events enable row level security;

drop policy if exists hq_worldcup_click_events_public_insert on public.hq_worldcup_click_events;
create policy hq_worldcup_click_events_public_insert
on public.hq_worldcup_click_events for insert to anon, authenticated
with check (
  char_length(worldcup_key) between 1 and 160
  and char_length(worldcup_title) between 1 and 500
  and char_length(coalesce(session_id, '')) <= 80
  and char_length(coalesce(path, '')) <= 500
  and char_length(coalesce(referrer, '')) <= 500
);

revoke all on public.hq_worldcup_click_events from anon, authenticated;
grant insert on public.hq_worldcup_click_events to anon, authenticated;
grant usage, select on sequence public.hq_worldcup_click_events_id_seq to anon, authenticated;

create or replace function public.hq_worldcup_click_stats(p_from date, p_to date)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with filtered as (
    select * from public.hq_worldcup_click_events
    where clicked_on between least(p_from, p_to) and greatest(p_from, p_to)
  ),
  daily as (
    select clicked_on, count(*)::bigint clicks, count(distinct session_id)::bigint visitors
    from filtered group by clicked_on order by clicked_on
  ),
  cups as (
    select worldcup_key, max(worldcup_title) worldcup_title, count(*)::bigint clicks,
      count(distinct session_id)::bigint visitors, max(clicked_at) last_clicked_at
    from filtered group by worldcup_key order by clicks desc, worldcup_title
  )
  select jsonb_build_object(
    'dateFrom', least(p_from, p_to),
    'dateTo', greatest(p_from, p_to),
    'totalClicks', (select count(*) from filtered),
    'uniqueVisitors', (select count(distinct session_id) from filtered),
    'daily', coalesce((select jsonb_agg(to_jsonb(daily) order by clicked_on) from daily), '[]'::jsonb),
    'worldcups', coalesce((select jsonb_agg(to_jsonb(cups) order by clicks desc, worldcup_title) from cups), '[]'::jsonb)
  );
$$;

revoke all on function public.hq_worldcup_click_stats(date, date) from public;
grant execute on function public.hq_worldcup_click_stats(date, date) to anon, authenticated;

commit;
