begin;
create extension if not exists pg_trgm;
create or replace function public.hq_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
create table if not exists public.hq_archive_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.hq_archive_subcategories (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.hq_archive_categories(id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (category_id, name),
  unique (id, category_id)
);
create table if not exists public.hq_archive_keywords (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.hq_archive_contents (
  id bigint generated by default as identity primary key,
  legacy_source_key text unique,
  title text not null,
  occurred_on date,
  source_url text,
  account text,
  category_id bigint references public.hq_archive_categories(id) on delete set null,
  subcategory_id bigint,
  keywords text[] not null default '{}',
  thumbnail_url text,
  status text not null default 'published' check (status in ('draft', 'published')),
  source_type text not null default 'manual' check (source_type in ('csv', 'manual', 'twitter')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint hq_archive_contents_subcategory_fk
    foreign key (subcategory_id, category_id)
    references public.hq_archive_subcategories(id, category_id)
    on delete set null
);
create table if not exists public.hq_worldcups (
  id bigint generated by default as identity primary key,
  legacy_cup_id text unique,
  title text not null,
  icon text not null default '🏆',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.hq_worldcup_candidates (
  id bigint generated by default as identity primary key,
  worldcup_id bigint not null references public.hq_worldcups(id) on delete cascade,
  legacy_candidate_id text,
  name text not null,
  occurred_on date,
  source_url text,
  media_url text,
  media_type text check (media_type is null or media_type in ('image', 'video', 'text')),
  width integer not null default 0 check (width >= 0),
  height integer not null default 0 check (height >= 0),
  poster_url text,
  win_count bigint not null default 0 check (win_count >= 0),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (worldcup_id, legacy_candidate_id)
);
drop trigger if exists hq_archive_categories_updated_at on public.hq_archive_categories;
create trigger hq_archive_categories_updated_at before update on public.hq_archive_categories
for each row execute function public.hq_set_updated_at();
drop trigger if exists hq_archive_subcategories_updated_at on public.hq_archive_subcategories;
create trigger hq_archive_subcategories_updated_at before update on public.hq_archive_subcategories
for each row execute function public.hq_set_updated_at();
drop trigger if exists hq_archive_keywords_updated_at on public.hq_archive_keywords;
create trigger hq_archive_keywords_updated_at before update on public.hq_archive_keywords
for each row execute function public.hq_set_updated_at();
drop trigger if exists hq_archive_contents_updated_at on public.hq_archive_contents;
create trigger hq_archive_contents_updated_at before update on public.hq_archive_contents
for each row execute function public.hq_set_updated_at();
drop trigger if exists hq_worldcups_updated_at on public.hq_worldcups;
create trigger hq_worldcups_updated_at before update on public.hq_worldcups
for each row execute function public.hq_set_updated_at();
drop trigger if exists hq_worldcup_candidates_updated_at on public.hq_worldcup_candidates;
create trigger hq_worldcup_candidates_updated_at before update on public.hq_worldcup_candidates
for each row execute function public.hq_set_updated_at();
create index if not exists hq_archive_contents_date_idx on public.hq_archive_contents (occurred_on desc, id desc);
create index if not exists hq_archive_contents_filter_idx on public.hq_archive_contents (status, category_id, subcategory_id, occurred_on desc);
create index if not exists hq_archive_contents_title_trgm_idx on public.hq_archive_contents using gin (title gin_trgm_ops);
create index if not exists hq_archive_contents_account_trgm_idx on public.hq_archive_contents using gin (account gin_trgm_ops);
create index if not exists hq_archive_contents_source_url_trgm_idx on public.hq_archive_contents using gin (source_url gin_trgm_ops);
create index if not exists hq_archive_contents_keywords_idx on public.hq_archive_contents using gin (keywords);
create index if not exists hq_worldcups_sort_idx on public.hq_worldcups (is_active, sort_order, id);
create index if not exists hq_worldcup_candidates_cup_idx on public.hq_worldcup_candidates (worldcup_id, is_active, sort_order, id);
create index if not exists hq_worldcup_candidates_rank_idx on public.hq_worldcup_candidates (worldcup_id, win_count desc, id);
alter table public.hq_archive_categories enable row level security;
alter table public.hq_archive_subcategories enable row level security;
alter table public.hq_archive_keywords enable row level security;
alter table public.hq_archive_contents enable row level security;
alter table public.hq_worldcups enable row level security;
alter table public.hq_worldcup_candidates enable row level security;
drop policy if exists hq_archive_categories_public_read on public.hq_archive_categories;
create policy hq_archive_categories_public_read on public.hq_archive_categories for select to anon, authenticated using (is_active);
drop policy if exists hq_archive_subcategories_public_read on public.hq_archive_subcategories;
create policy hq_archive_subcategories_public_read on public.hq_archive_subcategories for select to anon, authenticated using (is_active);
drop policy if exists hq_archive_keywords_public_read on public.hq_archive_keywords;
create policy hq_archive_keywords_public_read on public.hq_archive_keywords for select to anon, authenticated using (is_active);
drop policy if exists hq_archive_contents_public_read on public.hq_archive_contents;
create policy hq_archive_contents_public_read on public.hq_archive_contents for select to anon, authenticated using (status = 'published');
drop policy if exists hq_worldcups_public_read on public.hq_worldcups;
create policy hq_worldcups_public_read on public.hq_worldcups for select to anon, authenticated using (is_active);
drop policy if exists hq_worldcup_candidates_public_read on public.hq_worldcup_candidates;
create policy hq_worldcup_candidates_public_read on public.hq_worldcup_candidates for select to anon, authenticated using (is_active);
revoke insert, update, delete on public.hq_archive_categories from anon, authenticated;
revoke insert, update, delete on public.hq_archive_subcategories from anon, authenticated;
revoke insert, update, delete on public.hq_archive_keywords from anon, authenticated;
revoke insert, update, delete on public.hq_archive_contents from anon, authenticated;
revoke insert, update, delete on public.hq_worldcups from anon, authenticated;
revoke insert, update, delete on public.hq_worldcup_candidates from anon, authenticated;
grant select on public.hq_archive_categories, public.hq_archive_subcategories, public.hq_archive_keywords,
  public.hq_archive_contents, public.hq_worldcups, public.hq_worldcup_candidates to anon, authenticated;
create or replace view public.hq_archive_public
with (security_invoker = true)
as
select
  content.id,
  content.title,
  content.occurred_on,
  content.source_url,
  content.account,
  category.name as main_category,
  subcategory.name as sub_category,
  content.keywords,
  content.thumbnail_url,
  content.updated_at
from public.hq_archive_contents content
left join public.hq_archive_categories category on category.id = content.category_id
left join public.hq_archive_subcategories subcategory on subcategory.id = content.subcategory_id
where content.status = 'published';
grant select on public.hq_archive_public to anon, authenticated;
create or replace view public.hq_worldcup_public
with (security_invoker = true)
as
select
  cup.id,
  cup.legacy_cup_id,
  cup.title,
  cup.icon,
  cup.sort_order,
  count(candidate.id)::bigint as candidate_count
from public.hq_worldcups cup
left join public.hq_worldcup_candidates candidate
  on candidate.worldcup_id = cup.id and candidate.is_active = true
where cup.is_active = true
group by cup.id, cup.legacy_cup_id, cup.title, cup.icon, cup.sort_order;
grant select on public.hq_worldcup_public to anon, authenticated;
create or replace function public.hq_archive_today(
  p_month_day text,
  p_offset integer default 0,
  p_limit integer default 30
)
returns table (
  id bigint,
  title text,
  occurred_on date,
  source_url text,
  account text,
  main_category text,
  sub_category text,
  keywords text[],
  thumbnail_url text,
  total_count bigint
)
language sql
stable
security invoker
as $$
  select
    archive.id, archive.title, archive.occurred_on, archive.source_url, archive.account,
    archive.main_category, archive.sub_category, archive.keywords, archive.thumbnail_url,
    count(*) over() as total_count
  from public.hq_archive_public archive
  where to_char(archive.occurred_on, 'MM-DD') = p_month_day
  order by archive.occurred_on desc, archive.id desc
  offset greatest(p_offset, 0)
  limit least(greatest(p_limit, 1), 60);
$$;
grant execute on function public.hq_archive_today(text, integer, integer) to anon, authenticated;
create or replace function public.hq_record_worldcup_win(p_candidate_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  next_count bigint;
begin
  update public.hq_worldcup_candidates
  set win_count = win_count + 1
  where id = p_candidate_id and is_active = true
  returning win_count into next_count;
  if next_count is null then raise exception 'Candidate not found'; end if;
  return next_count;
end;
$$;
revoke all on function public.hq_record_worldcup_win(bigint) from public;
grant execute on function public.hq_record_worldcup_win(bigint) to anon, authenticated;
commit;
